//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq {
    
    
    public partial class how_to_add_a_LINQ_to_SQL_Item_to_the_Project {
    }
}
